In [1]:
import torch
import numpy as np
from ssl_wearables.hr_mamba import HRMambaRegressor


model = HRMambaRegressor(
    input_channels=3,
    seq_len=300,
    patch_size=15,
    stride=15,
    d_model=128,
    depth=6,
    d_state=16,
)

x = torch.randn(8, 300, 3)
y = model(x)

print(y.shape)

torch.Size([8, 1])


In [2]:
data = np.load(f"ssl_wearables/data/ssl/ssl_ai4wellness/data/train/user_000414.npz" ,mmap_mode='r') # file, mmap_mode=None
X, y = data["X"], data["hr"]

In [3]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")

Total parameters: 2,359,041


In [4]:
from torch.utils.data import Dataset, DataLoader,TensorDataset

# Convert NumPy arrays to PyTorch tensors
X_train = torch.tensor(X, dtype=torch.float32)  # Convert to float32
y_train = torch.tensor(y, dtype=torch.float32)  # Convert to long for classification

# Create DataLoader
train_dataset = TensorDataset(X_train, y_train)

train_loader = DataLoader(train_dataset, batch_size=512, shuffle=True)

In [5]:
x.shape

torch.Size([8, 300, 3])

In [7]:
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torch

device = "cuda:0" if torch.cuda.is_available() else "cpu"

# Convert NumPy arrays to PyTorch tensors
X_train = torch.tensor(X, dtype=torch.float32)
y_train = torch.tensor(y, dtype=torch.float32)

# Create DataLoader
train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(
    train_dataset,
    batch_size=512,
    shuffle=True
)

# Move model to GPU/CPU
model = model.to(device)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

epochs = 1

model.train()

for epoch in range(epochs):
    for x, hr in train_loader:
        x = x.to(device).float().view(-1, 300, 3)   # (B, 300, 3)
        hr = hr.to(device).float().view(-1, 1)      # (B, 1)

        pred_hr = model(x)

        loss = criterion(pred_hr, hr)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(loss.item())

5361.322265625
5406.8134765625
5465.41845703125
5385.9072265625
5395.8037109375
5475.2001953125
5337.7333984375
5504.9560546875
5101.7138671875
5359.052734375
5150.3017578125
5505.0419921875
5405.57763671875
5086.1640625
5293.06103515625
5234.64208984375
5333.7119140625
5064.4423828125
4870.50537109375
5303.71044921875
5033.548828125
5384.2177734375
5192.6708984375
5007.630859375
5177.876953125
5313.642578125
5397.70361328125
5034.8876953125
5356.98486328125
5219.7099609375
5069.6103515625
4946.845703125
5132.03466796875
5049.73291015625
5163.255859375
5308.2470703125
5275.298828125
5174.3203125
5002.17822265625
5134.62939453125
4990.03271484375
4884.041015625
4903.3623046875
5131.248046875
5410.39453125
5217.51171875
4952.3076171875
5267.1748046875
5041.06103515625
5338.50830078125
5233.640625
5190.84423828125
5242.06005859375
4989.59765625
4772.35546875
5139.0322265625
4717.0263671875
5044.0771484375
5274.4345703125
5134.966796875
5117.962890625
5017.830078125
4864.86328125
5235.4550

In [8]:
data = np.load(f"ssl_wearables/data/ssl/ssl_ai4wellness/data/train/user_03be38.npz" ,mmap_mode='r') # file, mmap_mode=None
X, y = data["X"][:1000], data["hr"][:1000]

In [11]:

# Convert NumPy arrays to PyTorch tensors
X_test = torch.tensor(X, dtype=torch.float32)  # Convert to float32
y_test = torch.tensor(y, dtype=torch.float32)  # Convert to long for classification
X_test= X_test.to(device)
model.eval()  # Set model to evaluation mode

with torch.no_grad():

    outputs = model(X_test.view(-1, 300, 3))  # Get raw logits

In [12]:
outputs

tensor([[7.4358],
        [7.4344],
        [7.4328],
        [7.4352],
        [7.4283],
        [7.4359],
        [7.4356],
        [7.4352],
        [7.4353],
        [7.4354],
        [7.4352],
        [7.4345],
        [7.4355],
        [7.4364],
        [7.4332],
        [7.4351],
        [7.4335],
        [7.4351],
        [7.4355],
        [7.4337],
        [7.4359],
        [7.4356],
        [7.4331],
        [7.4333],
        [7.4356],
        [7.4351],
        [7.4355],
        [7.4294],
        [7.4346],
        [7.4359],
        [7.4337],
        [7.4338],
        [7.4337],
        [7.4351],
        [7.4352],
        [7.4364],
        [7.4352],
        [7.4351],
        [7.4359],
        [7.4356],
        [7.4357],
        [7.4350],
        [7.4286],
        [7.4362],
        [7.4353],
        [7.4353],
        [7.4354],
        [7.4359],
        [7.4340],
        [7.4352],
        [7.4331],
        [7.4353],
        [7.4355],
        [7.4358],
        [7.4340],
        [7

In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression
data = np.load(f"ssl_wearables/data/ssl/ssl_ai4wellness/data/train/user_000414.npz" ,mmap_mode='r') # file, mmap_mode=None
X_train, y_train = data["X"], data["hr"]

#reg = LinearRegression().fit(X, y)

In [29]:
X_train = X_train.reshape(-1, 3)

In [30]:
X_train.shape, y_train.shape

((25845900, 3), (86153,))

In [31]:
y_train

array([61., 51., 54., ..., 98., 59., 62.], dtype=float32)

In [37]:
final_coisa = []
for i in y_train:
    final_coisa += [i]*300

In [41]:
X_train.shape , final_coisa.shape

((25845900, 3), (25845900,))

In [40]:
final_coisa = np.array(final_coisa)

In [42]:
import numpy as np
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_train, final_coisa)

In [43]:
data = np.load(f"ssl_wearables/data/ssl/ssl_ai4wellness/data/train/user_03be38.npz" ,mmap_mode='r') # file, mmap_mode=None
X_test, y_test = data["X"][:1000], data["hr"][:1000]

X_test = X_test.reshape(-1, 3)

final_coisa_test = []
for i in y_test:
    final_coisa_test += [i]*300

In [47]:
final_coisa.shape

(25845900,)

In [49]:
reg.predict(X_test)[::300]

array([66.409096, 66.71764 , 66.20682 , 66.47857 , 79.1411  , 67.33011 ,
       66.31675 , 74.06918 , 63.954445, 76.433334, 66.195175, 69.11641 ,
       73.8507  , 68.514114, 74.091286, 69.5677  , 68.9401  , 65.92578 ,
       72.69583 , 68.13769 , 64.25525 , 66.31965 , 73.37932 , 71.22824 ,
       68.73537 , 75.98564 , 69.473   , 83.12756 , 76.306984, 66.87071 ,
       64.5587  , 72.36269 , 69.78224 , 66.27904 , 65.90711 , 68.45752 ,
       70.55486 , 70.39859 , 76.6214  , 68.26786 , 72.32959 , 67.5397  ,
       70.171074, 66.977455, 70.14874 , 72.49823 , 67.999084, 78.41379 ,
       76.77403 , 71.7976  , 73.76731 , 73.988556, 72.27079 , 76.52666 ,
       75.91713 , 66.63916 , 66.427895, 65.94298 , 72.34467 , 65.39359 ,
       67.65007 , 68.07621 , 78.37192 , 76.528114, 69.9441  , 75.30756 ,
       66.65351 , 66.11331 , 77.50165 , 79.465866, 77.11023 , 71.71903 ,
       67.829926, 77.40215 , 68.762405, 72.94857 , 74.70016 , 67.48824 ,
       68.69538 , 72.19118 , 71.40834 , 72.54127 , 